spring.application.name=Cold-Wallet-Manager-Service
pkcs11.library.path=/usr/local/lib/libpkcs11-proxy.so

# JPA and Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
