spring.application.name=Cold-Wallet-Manager-Service
pkcs11.library.path=/usr/local/lib/libpkcs11-proxy.so

# JPA and Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Vault properties
spring.cloud.vault.uri=${SPRING_CLOUD_VAULT_URI:http://localhost:8200}

spring.cloud.vault.authentication=approle
spring.cloud.vault.app-role.role-id=${VAULT_ROLE_ID}
spring.cloud.vault.app-role.secret-id=${VAULT_SECRET_ID}
spring.cloud.vault.app-role.app-role-path=approle
